Vagrant.configure("2") do |config|
    config.vm.box = 'centos/7'
    config.vm.hostname = 'manager'
    config.vm.network 'forwarded_port', guest: 8081, host: 8081, hostip: '127.0.0.1'
    config.vm.network "private_network", ip: "192.168.57.25"
    config.vm.provider 'virtualbox' do |v| 
      v.memory =2048
    end
    
  end